// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twtotdnzacybtbaftlvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dG90ZG56YWN5YnRiYWZ0bHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Mjg4NDUsImV4cCI6MjA1OTEwNDg0NX0.QEP77pxiybAU4knZnoBLEwEFRkOvnZLsRkpyBzWwfdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);